### ISSUE TITLE
学习制作动态网页

### ISSUE THREAD

**Issue by OliverHao233** [FrankFang/fack#22]
自学过前端，但是没有独立完成过网页的制作，想学习一下系统的搭建网页

**Comment by FrankFang** [comment]
请说得更具体一点（举例说明）

**Comment by OliverHao233** [comment]
> 请说得更具体一点（举例说明）

搭建一个类似于知乎首页的网站，只完成页面的搭建和基本功能就可以

**Comment by FrankFang** [comment]
页面搭建很容易通过 vue-cli 和 create-react-app 完成。你是否想用框架我还不知道。
