### ISSUE TITLE
想使用react和typescript还有node做出一个项目

### ISSUE THREAD

**Issue by djknight1** [FrankFang/fack#3]
普通的项目我是可以实现的。。现在就是没有一个好的想法，同时发现自己平常使用typescript的特性几乎都是变量类型，没怎么用到他的高级技巧。想熟练掌握ts，同时在node方面想做一个稍微底层的应用，而不仅仅是crud 连接数据库等。
谢谢方方🙏

**Comment by FrankFang** [comment]
提问有效，但是有些矛盾。你想要的是
1. 用 TS 和 Node 写一个偏底层的应用
2. 用 React + TS 写一个网页应用

这两个，请二选一

**Comment by djknight1** [comment]
@FrankFang  确实矛盾了。主要想做的是第二点，然后可以自己使用React将底层得出的数据或者信息展现出来。
网页应用这一块不是那么重要，如果方方布置的任务不需要用到网页的话也是可以的

**Comment by smileboyi** [comment]
使用nest.js开发一个后台应用，前端框架可选react和angular。

**Comment by FrankFang** [comment]
请重新提交 Issue 描述你的目标。有具体的例子更好。@djknight1
