### ISSUE TITLE
想要用vue做一个功能齐全的dashboard

### ISSUE THREAD

**Issue by cxk0222** [FrankFang/fack#34]

**Comment by FrankFang** [comment]
# 任务一

https://github.com/FrankFang/fack/issues/15#issuecomment-496083097

请完成这个任务，答案回复在下方。

**Comment by cxk0222** [comment]
项目源码地址：https://github.com/Yuriuh/vue-lean-blog，
项目预览地址：https://yuriuh.github.io/vue-lean-blog/

**Comment by FrankFang** [comment]
# 任务二

https://github.com/FrankFang/fack/issues/15#issuecomment-496108128

请完成这个任务，答案回复在下方。

**Comment by FrankFang** [comment]
你好像已经完成了任务二。

**Comment by cxk0222** [comment]
对的，看到了 leanCloud 的 restful api，并简单应用了一下。请问接下来该做什么

**Comment by FrankFang** [comment]
# 任务三：使用 Vue Router

请用 vue-cli 创建一个应用，满足以下要求

1. 安装 Vue Router，使用 Hash 模式路由
2. 用户访问 localhost:8080/#/1，页面中会出现 1
3. 用户访问 localhost:8080/#/2，页面中会出现 2

请提交预览链接。

**Comment by cxk0222** [comment]
预览地址：https://yuriuh.github.io/vue-fang/
（ps: 最近工作比较忙，提交晚了还请方方见谅）
