### ISSUE TITLE
想学习用vue＋typescript造个简单的ui轮子，最好包含单元测试

### ISSUE THREAD

**Issue by squall1744** [FrankFang/fack#40]
老师，我是1802B班毕业的毕业生，工作了半年了，想学习单元测试和造轮子，初步想法想尝试用vue＋ts学习造轮子，轮子包括单元测试，但是没有头绪，求老师帮忙

**Comment by FrankFang** [comment]
Vue + TS 目前不是一个好搭配（我不熟悉），推荐你学习 React + TS

**Comment by squall1744** [comment]
那react + ts 造轮子 + 单元测试也行。。老师有啥推荐没, react虽然工作中没用过, 但是之前学的时候用react做过项目, 现在应该过一遍文档也能拿起来

**Comment by FrankFang** [comment]
这个要用文字一步一步教还挺久的，我有收费课程你可以看下 https://xiedaimala.com/courses/f720115a-c84f-4339-8852-951a86840cdd

已经讲了 80 多个视频了。

这个 issue 就关闭了，无法很好地用文字解决。
