### ISSUE TITLE
想进阶前端，为秋招做准备

### ISSUE THREAD

**Issue by raintygao** [FrankFang/fack#49]
方方老师您好，我是一名大三学生，春招拿到了tx的offer，过段时间就要去实习了，想要在秋招前(大概一个半月左右的时间)进阶，争取秋招拿到更好的offer或者sp之类的～目前情况是基础比较好，算法暂时不考虑，技术栈是react+node，方方老师可以给点任务、建议或者看哪些书视频之类的吗？希望简历上可以增色一些东西以及针对校招提高自己的能力 谢谢方大🙏

**Comment by FrankFang** [comment]
简历增色的话就是做项目了。你想做什么样的。

**Comment by raintygao** [comment]
项目考虑过，但是小型以上的项目应该没有太多时间，因为时间也比较碎片化，刚看了下您的wheels仓库，方大认为造轮子怎么样呢？如果可以的话可以给我个题 😊谢谢🙏

**Comment by FrankFang** [comment]
造轮子的难点在于项目搭建和单元测试。不太适合这样教学。不过你可以试试。

# 任务一：React 轮子环境搭建

参考我的命令 https://github.com/jrg-team/guui-react/blob/master/package.json#L23

尝试用 webpack 搭建一个项目，要求：

1. yarn start 开启 webpack-dev-server
2. yarn build 会打包出一个 xxx.js（可以有多余的 html 文件）
3. 打包的时候不要把 React 相关的库打包进去

你也可以不参考我的，自己搜 webpack lib config

搭建成功后回复 github repo 链接。
