### ISSUE TITLE
关于转行面试一份前端工作10-15K之间的项目要求

### ISSUE THREAD

**Issue by ThomasZJH** [FrankFang/fack#51]
方老师你好，我目前在转行学习前端，因为简历上要求有项目经验，而这对于我这样转行的人要求很难，毕竟没在互联网公司工作过，而且也没做过类似的岗位，靠自学和一些培训课程学习前端的，所以对项目这块，能做到什么程度，什么能力，才可能应聘10-15K这个级别的前端工作，还望方老师指导下。目前在学习Vue基础，跟着慕课网买的实战课(做去哪儿app)跟着学做项目，但心里没底，不知道这样的项目能否写到简历里，或者方老师有更好的实战项目，还望多多指点下，麻烦了。

**Comment by FrankFang** [comment]
我确实是有更好的实战项目，但是是收费的哦。https://xiedaimala.com/courses/f720115a-c84f-4339-8852-951a86840cdd
