### ISSUE TITLE
我想拖延的目标在9月份前落地

### ISSUE THREAD

**Issue by wheadplus** [FrankFang/fack#57]
三四线城市工作俩三个月的前端。像松鼠一样，我囤了很多课程。拖延的课程大概：
- vue造轮子（三月前已完成初级，中高级无限拖延中）
- 小程序番茄钟（加载中）
- 算法（没开始）
- vue小米商城（没开始）

目前有 2 个问题：
1.  **学过的东西老是忘记**
2.  **拖延和执行问题**

我下班大概有3个小时的学习时间，也就是6个番茄的时间。（实际每天最多3-4番茄）（6天班周日咸鱼）

关于拖延，我大概有个想法，一天如果能完成5个番茄奖励 x 元,没有则减少 x/2 元。一周有5天完成奖励 3x 元。

**Comment by FrankFang** [comment]
1. 不要用番茄工作法，用「骗自己只做五分钟」工作法
2. 忘了没问题，只要你的项目上传到 GitHub 留下绿点就行

每天骗自己：我只写五分钟代码。五分钟后就不写。效果显著。
