### ISSUE TITLE
想学习移动端页面开发

### ISSUE THREAD

**Issue by ymjrcc** [FrankFang/fack#7]
入行几年，因为公司业务关系，做的大部分都是 PC 浏览器页面相关的业务，因为移动端是大势所趋，就想在这方面多学习，丰富自己的技能树。目前只了解简单零碎的相关知识点，想通过开发项目的方式来提高自己这方面的能力。

希望自己完成任务后能够熟悉移动端页面开发的流程，知晓它与 PC 端页面开发的区别和注意事项，有能力从 0 到 1 完成一个移动端项目前端页面开发工作。

谢谢方方！

**Comment by FrankFang** [comment]
# 任务一：学会使用 GitHub Pages
请学会使用 GitHub Pages 部署网页。
答题要求：给出一个你自己部署的 GitHub Pages 页面的预览链接即可。

有疑问请留言。

**Comment by ymjrcc** [comment]
https://ymjrcc.github.io/ 
@FrankFang

**Comment by ymjrcc** [comment]
> # 任务一：学会使用 GitHub Pages
> 请学会使用 GitHub Pages 部署网页。
> 答题要求：给出一个你自己部署的 GitHub Pages 页面的预览链接即可。
> 
> 有疑问请留言。

**Comment by FrankFang** [comment]
# 任务二：使用媒体查询

新建一个仓库写代码，要求如下

1. 当页面宽度小于等于 500，页面全部都是红色背景
2. 当页面宽度大于 500 小于等于 800，页面全部都是绿色背景
3. 当页面宽度大于 800，页面全部都是蓝色背景
4. 页面中有一张图片，图片宽度跟页面永远保持一致（使用 img 标签）
5. 页面禁止用户缩小放大（使用 meta 标签）

**Comment by ymjrcc** [comment]
仓库代码：https://github.com/ymjrcc/learn-mobile/blob/master/step02/index.html
预览地址：https://ymjrcc.github.io/learn-mobile/step02/

@FrankFang

**Comment by FrankFang** [comment]
问题：
1. user-scalable=0; 应该是 user-scalable=no; 吧？  请查出正确的写法
2. min-width: 500px 应该是 501px；(min-width: 800px) 应该是 801 px

**Comment by FrankFang** [comment]
# 任务三：模仿百度手机版

请用 Chrome 开发者里面的手机模拟器打开 baidu.com，将下图中红线圈起来的部分实现出来。没有圈起来的部分留白即可。

![image](https://user-images.githubusercontent.com/839559/58425416-5472bc80-80cc-11e9-8030-a9407f37c502.png)

要求：

1. 点击左上角的「三」可以慢慢滑出一个浮层，浮层可以是纯白的 div，但是高度必须跟百度做得一样
2. 输入框的宽度会自适应，但是输入框右边的 icon 大小不会变
3. 不用理会 PC 端的效果。

请新开一个文件或者新开一个仓库实现这个效果，然后把预览链接放在下面。

**Comment by ymjrcc** [comment]
任务二指出的问题已经改了。

任务三：
预览链接：https://ymjrcc.github.io/learn-mobile/step03/
代码链接：https://github.com/ymjrcc/learn-mobile/tree/gh-pages/step03
（我打开百度首页没有你截图里右上角的金币 icon，所以就没画，其他的都实现了）

@FrankFang

**Comment by FrankFang** [comment]
# 任务四：使用 React 改写你的应用

把你的代码改成 React 写的，可以使用 create-react-app 来初始化应用。

请新开一个仓库实现这个效果，然后把预览链接放在下面。

提示：如果你不会 React 可以提出，不过我建议你先尝试看看。

**Comment by ymjrcc** [comment]
上面应该是任务四。

预览链接：https://ymjrcc.github.io/learn-mobile-react/build/
代码链接：https://github.com/ymjrcc/learn-mobile-react
（有过近两年 React 开发经验）

@FrankFang

**Comment by FrankFang** [comment]
# 任务五：使用 React Router

新建一个应用（不要用原来的），满足以下要求

1. 安装 React Router，使用 Hash 模式路由（先不要使用 History 模式）
2. 用户访问 localhost:8080/#/1，页面中会出现 1
3. 用户访问 localhost:8080/#/2，页面中会出现 2
3. 用户访问 localhost:8080/，页面中会出现你目前做的百度应用

代码需要上传到 GitHub，回复给我

1. 代码链接
2. 预览链接

**Comment by FrankFang** [comment]
那你有 React 开发经验，还要学习移动端页面开发，其实就是在学习 CSS 啊。
你是想做一个自己的应用么？
如果你觉得目前的任务太简单可以说出来

**Comment by ymjrcc** [comment]
> 那你有 React 开发经验，还要学习移动端页面开发，其实就是在学习 CSS 啊。
> 你是想做一个自己的应用么？
> 如果你觉得目前的任务太简单可以说出来

目前的任务感觉是比较简单。React Router，Redux，还有阿里那一套 dva、ant design 什么的我都比较熟悉，毕竟之前天天开发都在用的。我想学习移动端页面开发，是在有 PC 浏览器网页开发经验的基础上，想要掌握移动端网页开发的要点和难点，看自己有什么薄弱的地方可以补上短板。之前也了解一些移动端网页开发的知识，比如布局方案、点击穿透、1px 边框什么的，但感觉不成系统，所以想多学习一下。如果是你说的那样，其实就是在学 CSS，那好像的确没有专门去学习的必要了？。。。

想做一个应用的想法也是有的，这个月开始在学习 Dart 和 flutter，这个打算自己在空闲的时候慢慢去摸索，就不在这里提了。

那方方你看这个任务还有必要进行下去吗，还是说我再想个别的任务来做？
@FrankFang

**Comment by FrankFang** [comment]
移动页面开发跟pc页面开发没有什么区别，就是屏幕小一点。建议你学flutter
