### ISSUE TITLE
协同其他同事开发react项目

### ISSUE THREAD

**Issue by 499800157** [FrankFang/fack#9]
所处情况：目前还没事实际开发过react或vue的项目，只是在视频中的学习和独自练习。
目的：是想能够适应项目中的业务。

**Comment by FrankFang** [comment]
# 任务一：索要任务

请向业务主管索要一个最简单的任务，然后把任务要求提供给我（请不要透露给我任何敏感内容，包括公司名、业务名）

如果有代码，可以将代码脱敏后，存放到 codesandbox.io 然后把 url 提供给我。

**Comment by 499800157** [comment]
目前是一个人在公司中撑起的前端业务。（也不知道能够拿什么任务来训练自己达到求职市场的开发要求，偏向react方向）
想要达到的水平：跳槽至其他公司能够适应正常的开发工作。
我想让方老帮助的：能够布置一些日常开发工作中所需要的技术点的任务。

**Comment by FrankFang** [comment]
你的目标太笼统，需要具体的一个一个任务，没有办法教你所有任务的解法。
你可以重开一个 issue，比如你想用 React 做一个应用等。

**Comment by 499800157** [comment]
好的，感谢。我先参考其他同学的issue
